spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/nba_player_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

server:
  port: 8080